### ISSUE TITLE
Should I tokenize the reference files when computing BLEU ?

### ISSUE THREAD

**Issue by Aolius** [laihuiyuan/Pre-trained-formality-transfer#1]
Hi, thank you for sharing your code with us. It is very useful.

I have a question regarding the BLEU score.
I noticed that we should do tokenization for prediction files in pg.sh before running multi-bleu.perl:
https://github.com/laihuiyuan/Pre-trained-formality-transfer/blob/2c9531cd16bf304773d55ea6b11ffe3d359c6abe/pg.sh#L19
However, since it is not written in pg.sh,  I wonder if the same tokenization should be applied to those reference files. I found the result very bad if I did not tokenize the reference files.

**Comment by laihuiyuan** [comment]
Hi! Thanks for your interest in our work. 
Yes! We should do the same tokenization for human references as well before calculating BLEU.

**Comment by Aolius** [comment]
Thank you! I got the correct results.
