### ISSUE TITLE
How did you get the test.0 file?

### ISSUE THREAD

**Issue by Barry-Menglong-Yao** [laihuiyuan/Pre-trained-formality-transfer#2]
Hi, thank you for sharing your code with us. It is very useful.

I have a question regarding the input file. How did you get the test.1 file? Is it the "test/formal" file from the GYAFC dataset? 
I believe the test.0 file is the "test/informal" file from the GYAFC dataset. Thanks.

**Comment by laihuiyuan** [comment]
Hi! Yes, exactly! The test.1 is the file containing source formal sentences from GYAFC, and the same is for test.0.

**Comment by MinJeongwon** [comment]
Hi! thanks for sharing your code.

I used train/informal of GYAFC_Corpus as train.1 and train/formal as train.0
As you mentioned above, I used test/informal as test.1 and test/formal as test.0
Then, what kind of data should I use for valid.0 and valid.1? Are they tune/informal and tune/formal respectively?

Thanks ahead for your reply.

**Comment by laihuiyuan** [comment]
Yes, exactly!
