### ISSUE TITLE
Could you help me with the cal_reward_loss fucntion？

### ISSUE THREAD

**Issue by KpKqwq** [laihuiyuan/Pre-trained-formality-transfer#3]
I found that the reward loss use negative log loss. When minimizing the reward loss,  it seems like it encourages  lower bleu scores?

**Comment by laihuiyuan** [comment]
Hi, rewards can be considered as weights to the negative log-likelihood loss,  a higher weight (reward) is equivalent to encouraging the model to generate these kinds of sentences, thus increasing the reward expectation of the model.

**Comment by KpKqwq** [comment]
Thanks for you reply!
