### ISSUE TITLE
How to calculate the accuracy according to multiple references?

### ISSUE THREAD

**Issue by StevenTang1998** [laihuiyuan/Pre-trained-formality-transfer#5]
Hi, I found one of the metric is the style accuracy to evaluate whether the generated sentence and the reference sentence has the same style label. The GYAFC dataset has four reference sentences and I wonder how to get a label of four references?

**Comment by laihuiyuan** [comment]
Hi, style accuracy is a reference-free metric, you just need a binary style classifier (informal vs formal) to evaluate the given sentence.

**Comment by StevenTang1998** [comment]
Thanks for your reply. But I wonder if so, why the [code](https://github.com/laihuiyuan/pre-trained-formality-transfer/blob/main/classifier/test.py) need to compare `0.txt` and `1.txt`.

**Comment by laihuiyuan** [comment]
This is not a comparison but the evaluation of the outputs of the two transfer directions.

**Comment by StevenTang1998** [comment]
Thanks! I understand it now.

**Comment by StevenTang1998** [comment]
However, I use it to evaluate the files under [outputs](https://github.com/laihuiyuan/pre-trained-formality-transfer/tree/main/outputs).
The result of em is 74.5396%.
The result of fr is 72.3522%.

They seem strange.

**Comment by laihuiyuan** [comment]
I guess you can check the dependencies, especially the version of transformers.

**Comment by StevenTang1998** [comment]
Oh yes! After changing the version of transformers, I can get satisfactory results, now!!

Best wishes!
