### ISSUE TITLE
Using the provided output cannot reproduce the result for BLEURT and ACC

### ISSUE THREAD

**Issue by MichaelCaohn** [laihuiyuan/Pre-trained-formality-transfer#9]
Hi authors,

Thank you very much for the work! It's very helpful. I tried to evaluate the outputs you provided in the output folder. 

For EM, I get the following results: 
ACC: 0.9031
BLUE: 0.7650
BLEURT: 0.044

I think the result I obtained matches the reported result under BLUE. However, the reported result for ACC is 0.929, and BLEURT is 0.274. 

I used the following command to calculate the ACC: "python classifier/test.py -dataset em -order 0.0.0",
and I use the following command to calculate the BLEURT: "python utils/cal_bleurt.py data/em/outputs/bart_em.0 data/em/outputs/bart_em.1 data/em/original_ref/formal.ref data/em/original_ref/informal.ref"

"data/em/outputs/bart_em.0" is the tokenized file for the file outputs/bart_em.0.txt, "data/em/outputs/bart_em.1" is the tokenized file for the file outputs/bart_em.1.txt, "data/em/original_ref/formal.ref" is the tokenized file for all the four formal references (formal.ref0, formal.ref1, formal.ref2, formal.ref3, and formal.ref4), and similarly "data/em/original_ref/informal.ref" is the tokenized file for all the four informal references (informal.ref0, informal.ref1, informal.ref2, informal.ref3, and informal.ref4). For the tokenization code, I use the "utils/tokenizer.py" provided by you. The BLEURT is installed from here: https://github.com/google-research/bleurt#installation, and downloaded the "bleurt-base-128" model from https://storage.googleapis.com/bleurt-oss/bleurt-base-128.zip 

I also tried to use the detokenized files when calculating the BLEURT score, which has a score of 0.078, which is still below the reported score.

Please let me know if there is anything I did wrong.

Thank you and looking forward to your reply.

Best regards

**Comment by laihuiyuan** [comment]
Hi! Thanks for your interest in our work. 

We used detokenized files to calculate Acc and BLEURT scores. For Acc, if you use our classifier, please use the checkpoint 'textcnn_em_gpt2.chkpt' to evaluate EM outputs. For BLEURT, we used the same model as you. I would suggest checking the dependencies such as PyTorch and Transformers versions.

**Comment by MichaelCaohn** [comment]
Hi,

Thank you very much for the reply. For the Acc result, I tried to load the 'textcnn_em_gpt2.chkpt' checkpoint, by changing [line 61](https://github.com/laihuiyuan/pre-trained-formality-transfer/blob/main/classifier/test.py#L61C5-L62C23) to:

```
model.load_state_dict(torch.load('./checkpoints/textcnn_em_gpt2.chkpt'))
```
and I didn't change the rest of the code. 

However, it returns me the following error message:

```
main()                                                                                                                                                     
File "classifier/test.py", line 65, in main
    model.load_state_dict(torch.load('./checkpoints/textcnn_em_gpt2.chkpt'))
File "/home/user/miniconda3/envs/easse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TextCNN:
        size mismatch for embeder.embeding.weight: copying a param with shape torch.Size([50262, 300]) from checkpoint, the shape in current model is torch.Size([50265, 300]).
```

I am wondering if this is the correct way to do it?

Looking forward to your reply.

Best regards,
Michael

**Comment by laihuiyuan** [comment]
Hi! you should comment [line25](https://github.com/laihuiyuan/pre-trained-formality-transfer/blob/main/classifier/test.py#L25) and uncomment [lines 26-28](https://github.com/laihuiyuan/pre-trained-formality-transfer/blob/main/classifier/test.py#L26-L28)
